import streamlit as st

st.set_page_config(page_title="Pricing Profitability Dashboard", layout="wide")

kpis = [
    {
        "name": "Risk-adjusted return on capital",
        "value": "14.2%",
    },
    {
        "name": "Regulatory capital",
        "value": "$86.7M",
    },
    {
        "name": "Economic Capital",
        "value": "$79.3M",
        "framework": "Basel II framework",
    },
]

st.markdown(
    """
    <style>
      :root {
        --bg: #fafafa;
        --surface: #ffffff;
        --text-primary: #000000;
        --text-secondary: #666666;
      }

      .stApp {
        background: var(--bg);
      }

      .dashboard-shell {
        max-width: 900px;
        margin: 0 auto;
        background: var(--surface);
        padding: 64px 48px;
      }

      .dashboard-title {
        font-size: 32px;
        line-height: 40px;
        letter-spacing: -1.6px;
        color: var(--text-primary);
        margin: 0;
      }

      .dashboard-subtitle {
        font-size: 16px;
        line-height: 28px;
        color: var(--text-secondary);
        margin: 12px 0 28px;
      }

      .kpi-grid {
        display: grid;
        grid-template-columns: repeat(3, minmax(0, 1fr));
        gap: 16px;
      }

      .kpi-card {
        border: 1px solid #e8e8e8;
        border-radius: 16px;
        padding: 20px;
      }

      .kpi-name {
        font-size: 13px;
        font-weight: 500;
        color: var(--text-secondary);
        margin: 0 0 12px;
      }

      .kpi-value {
        font-size: 22px;
        font-weight: 600;
        line-height: 1.2;
        color: var(--text-primary);
        margin: 0;
      }

      .kpi-framework {
        display: inline-block;
        margin-top: 8px;
        font-size: 11px;
        color: var(--text-secondary);
      }

      @media (max-width: 900px) {
        .dashboard-shell {
          padding: 32px 20px;
        }

        .kpi-grid {
          grid-template-columns: 1fr;
        }

        .dashboard-title {
          font-size: 28px;
          line-height: 34px;
          letter-spacing: -1.2px;
        }
      }
    </style>
    """,
    unsafe_allow_html=True,
)

cards_markup = ""
for kpi in kpis:
    framework = (
        f'<span class="kpi-framework">{kpi["framework"]}</span>' if "framework" in kpi else ""
    )
    cards_markup += f"""
      <article class="kpi-card">
        <p class="kpi-name">{kpi['name']}</p>
        <p class="kpi-value">{kpi['value']}</p>
        {framework}
      </article>
    """

st.markdown(
    f"""
    <main class="dashboard-shell">
      <h1 class="dashboard-title">Pricing Profitability Dashboard</h1>
      <p class="dashboard-subtitle">Key performance indicators generated by the latest pricing run.</p>
      <section class="kpi-grid" aria-label="KPI output">
        {cards_markup}
      </section>
    </main>
    """,
    unsafe_allow_html=True,
)
