import styles from "./page.module.css";

const kpis = [
  {
    name: "Risk-adjusted return on capital",
    value: "14.2%",
  },
  {
    name: "Economic profit",
    value: "$12.4M",
  },
  {
    name: "Regulatory capital",
    value: "$86.7M",
  },
];

export default function Home() {
  return (
    <div className={styles.page}>
      <main className={styles.main}>
        <div className={styles.intro}>
          <h1>Pricing Profitability Dashboard</h1>
          <p>Key performance indicators generated by the latest pricing run.</p>
        </div>

        <section className={styles.kpiSection} aria-label="KPI output">
          {kpis.map((kpi) => (
            <article className={styles.kpiCard} key={kpi.name}>
              <h2>{kpi.name}</h2>
              <p>{kpi.value}</p>
            </article>
          ))}
        </section>
      </main>
    </div>
  );
}
