import styles from "./page.module.css";

type Kpi = {
  name: string;
  value: string;
  framework?: string;
};

const kpis: Kpi[] = [
  {
    name: "Risk-adjusted return on capital",
    value: "14.2%",
  },
  {
    name: "Regulatory capital",
    value: "$86.7M",
  },
  {
    name: "Economic Capital",
    value: "$79.3M",
    framework: "Basel II framework",
  },
];

export default function Home() {
  return (
    <div className={styles.page}>
      <main className={styles.main}>
        <div className={styles.intro}>
          <h1>Pricing Profitability Dashboard</h1>
          <p>Key performance indicators generated by the latest pricing run.</p>
        </div>

        <section className={styles.kpiSection} aria-label="KPI output">
          {kpis.map((kpi) => (
            <article className={styles.kpiCard} key={kpi.name}>
              <h2>{kpi.name}</h2>
              <p>{kpi.value}</p>
              {kpi.framework ? <span>{kpi.framework}</span> : null}
            </article>
          ))}
        </section>
      </main>
    </div>
  );
}
